In [1]:
import pandas as pd
from sqlalchemy import (create_engine, Float, Text, MetaData, Table, Column, Integer, String, PrimaryKeyConstraint, ForeignKey)
df = pd.read_csv('/Users/hamza.ahmed/Library/Containers/com.microsoft.Excel/Data/Downloads/Benchmade - Sheet2.csv')

In [2]:
df

,Knife_id,Name,Price,Blade_Length,Blade_Material,Blade_Grind,Blade_Finish
0,1,4010-211 COLLECTORS EDITION STATION KNIFE,1500.0,5.97,Damasteel (58-60HRC),NaN,Etched
1,2,4000-211 COLLECTORS EDITION 3 PIECE SET,2400.0,8.04,Damasteel (58-60HRC),NaN,Etched
2,3,602-211 TENGU TOOL,350.0,1.14,CPM-D2 (60-62 HRC),NaN,Cobalt Black
3,4,9070BK-1 CLAYMORE™,230.0,3.60,CPM-D2 (60-62 HRC),NaN,Cobalt Black
4,5,9070BK CLAYMORE™,230.0,3.60,CPM-S30V (58-60 HRC),NaN,Stonewash
...,...,...,...,...,...,...,...
139,140,178SBK SOCP,180.0,3.22,NaN,NaN,NaN
140,141,SOCP 178SBK-COMBO,360.0,3.22,NaN,NaN,NaN
141,142,SOCP 178SBKSN,165.0,3.22,NaN,NaN,NaN
142,143,945-221 MINI OSBORNE,700.0,NaN,Damasteel (58-60HRC),NaN,Damasteel
143,144,Phaeton® Family,180.0,NaN,CPM-S30V (58-60 HRC),NaN,NaN

In [3]:
db_connection= 'postgresql+psycopg2://postgres:DataIsConfusing2022@localhost/sql_demo2'
engine = create_engine(db_connection)
df.to_sql('pandas_db', engine)

ValueError: Table 'pandas_db' already exists.